CREATE TABLE shops(id int,name varchar(100),location varchar(100), type_of_shop varchar(100), owner_name varchar(100), opening_time varchar(100),closing_time varchar(100),size_of_shop bigint,no_of_customers int,no_of_employees int,land_mark varchar(100),direction varchar(100));
SELECT * from shops;
ALTER TABLE shops ADD COLUMN employee_names varchar(100),ADD COLUMN color_of_shop varchar(100);
insert into shops values(1,'max','bangalore','cloth','shweta','10_am','10_pm',1200,100,10,'ramandira','north_facing','girish','white');
insert into shops values(2,'pharmacy','gangavathi','medical','rekha','11_am','9_pm',600,50,3,'beside_dental_clinic','west_facing','prasanna','green');
insert into shops values(3,'trends','raichur','cloth','niranjana','9_am','8_pm',3000,500,5,'beside hanuman temple','north_facing','sushma','pink');
insert into shops values(4,'pavitra','bangalore','baby products','prabha','9_am','8_pm',600,200,10,'mruthajaya temple','north_east_facing','girish','pale_yellow');
insert into shops values(5,'sudharashana','bangalore','saree','suraj','11_am','9_pm',1800,300,20,'chickhpet','west_facing','suma','gold');
insert into shops values(6,'oppo','gangavathi','phone','gururaj','10_am','9_pm',1200,100,5,'ghandi circle','east_facing','suresh','white');
insert into shops values(7,'ambika','gangavathi','electronic devices','rathanalal','10_am','10_pm',1500,100,5,'mahaveer circle','north_facing','mukesh','white');
insert into shops values(8,'brundhavana','sidhnur','food','brundha','7_am','10_pm',2000,500,30,'beside bustand','south_facing','anurag','green');
insert into shops values(9,'amardeep','sindhnur','sarees','shweta','10_am','10_pm',1000,250,10,'kanakdas circle','east_facing','mukesh','white');
insert into shops values(10,'TVS','gangavthi','automobiles','sanjeevakumar','11_am','9_pm',2100,100,15,'ranaprathapa','north_facing','abdul','white');
insert into shops values(11,'savariya','lakshmeshwar','chats','rekha','5_pm','10_pm',300,100,3,'ganja circle','west_facing','girish','white');
insert into shops values(12,'durga','lingasur','food','durga','7_am','10_pm',2000,400,25,'bustand road','north_east_facing','raj','orange');
insert into shops values(13,'sajana','sindhnur','stationary','priyanka','9_30_am','9_pm',300,100,3,'ramandira','north_facing','girish','white');
insert into shops values(14,'asian paints','gangavathi','paint','ragvendra','10_am','10_pm',1200,100,10,'ramandira','north_facing','girish','white');
insert into shops values(15,'nylon','sindhnur','pipe','shweta','10_am','10_pm',600,100,10,'ramandira','north_facing','niranjana','yellow');
insert into shops values(16,'zudio','bangalore','cloth','shetty','11_am','10_pm',1000,500,25,'lulu mall','west_facing','deepa','white');
insert into shops values(17,'penter england','gangavathi','watch','arun','10_am','10_pm',600,100,10,'kanakagiri road','north_facing','surendra','pink');
insert into shops values(18,'vivo','bangalore','phone','latha','10_am','10_pm',1200,100,5,'gandhicircle','north_south_facing','farag','white');
insert into shops values(19,'anapurana','gangavathi','electronics devices','anapurana','11_am','11_pm',2000,300,10,'mahaveer circle','east_facing','sagar','creame');
insert into shops values(20,'bata','bangalore','footware','shweta','9_am','10_pm',2500,200,50,'majestic','north_facing','abhishek','white');

select * from shops where location='gangavathi';
select * from shops where type_shop='medical';
select * from shops where owner_name='shweta';
select * from shops where name='max';
select * from shops where employee_names='abhishek';
